---
- hosts: database
  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
      become: yes  

  tasks:
    - name: 'Instala pacotes de dependencia do MySQL'
      apt:
        update_cache: yes
        cache_valid_time: 7200 #2 hours
        name: "{{ item }}"
        state: latest
      become: yes
      loop:
        - mysql-server-5.7
        - python3-mysqldb

    - name: 'Cria uma database no MySQL'
      mysql_db:
        name: "{{ wp_db_name }}"
        login_user: root        
        state: present
      become: yes

    - name: 'Criar usuario no MySQL'
      mysql_user:
        login_user: root
        name: "{{ wp_username }}"
        password: "{{ wp_userpass }}"
        priv: "{{ wp_db_name }}.*:ALL"
        host: '%'
        state: present
        host: "{{ item }}"
      loop:
        - 'localhost'
        - '127.0.0.1'
        - "{{ wp_host_ip }}"          
      become: yes

    - name: 'Copiando arquivo mysqld.cnf'
      copy:
        src: /vagrant/configs/mysql/mysqld.cnf
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        owner: root
        group: root
        mode: 0644
      become: yes  

      notify: 
        - restart mysql 

- hosts: wordpress
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
      become: yes

  tasks:
    - name: 'Instala pacotes de dependencia do PHP+Apache'
      apt:
        update_cache: yes
        cache_valid_time: 7200 #2 hours
        name: "{{ item }}"
        state: latest
      become: yes
      loop:
        - php7.2
        - apache2
        - libapache2-mod-php7.2
        - php7.2-gd
        - php7.2-mysql               

    - name: 'Download Arquivo Wordpress'
      ansible.builtin.get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: /tmp/wordpress.tar.gz      
      become: yes

    - name: 'Descompacta o Wordpress'        
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/
        remote_src: yes
      become: yes

    - name: 'Copiando arquivo de configuracao wordpress'
      copy:
        src: "{{ wp_installation_dir }}/wp-config-sample.php"
        dest: "{{ wp_installation_dir }}/wp-config.php"
        remote_src: yes
      become: yes

    - name: 'Configura o wp-config com as entradas do banco de dados'
      replace:
        path: "{{ wp_installation_dir }}/wp-config.php"
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"        
      loop:
        - { regex: 'database_name_here', value: "{{ wp_db_name }}"}
        - { regex: 'username_here', value: "{{ wp_username }}"}
        - { regex: 'password_here', value: "{{ wp_userpass }}"}
        - { regex: 'localhost', value: "{{ wp_dp_ip }}"}
      become: yes

    - name: 'Configura Apache para servir Wordpress'
      template:
        src: '/vagrant/configs/ansible/templates/000-default.conf.j2'
        dest: '/etc/apache2/sites-available/000-default.conf'
      become: yes

    - name: 'Configura porta do apache para servir wordpress'
      template:
        src: '/vagrant/configs/ansible/templates/ports.conf.j2'
        dest: '/etc/apache2/ports.conf'
      become: yes

      notify:              
        - restart apache

