---
- name: 'Instala pacotes de dependencia do MySQL'
  apt:
    update_cache: yes
    cache_valid_time: 7200 #2 hours
    name: "{{ item }}"
    state: latest
  become: yes
  loop:
    - mysql-server-5.7
    - python3-mysqldb

- name: 'Cria uma database no MySQL'
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: root        
    state: present
  become: yes

- name: 'Criar usuario no MySQL'
  mysql_user:
    name: "{{ wp_username }}"
    login_user: root
    password: "{{ wp_userpass }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: "{{ item }}"
  become: yes
  loop:
    - 'localhost'
    - '127.0.0.1'
    - "{{ wp_host_ip }}"          

- name: 'Copiando arquivo mysqld.cnf'
  copy:
    src: 'mysqld.cnf'
    dest: '/etc/mysql/mysql.conf.d/mysqld.cnf'
    owner: root
    group: root
    mode: 0644
  become: yes  

  notify: 
    - restart mysql 