---
- name: 'Download Arquivo Wordpress'
  ansible.builtin.get_url:
    url: 'https://wordpress.org/latest.tar.gz'
    dest: /tmp/wordpress.tar.gz      
  become: yes

- name: 'Descompacta o Wordpress'        
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/
    remote_src: yes
  become: yes

- name: 'Copiando arquivo de configuracao wordpress'
  copy:
    src: "{{ wp_installation_dir }}/wp-config-sample.php"
    dest: "{{ wp_installation_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: 'Configura o wp-config com as entradas do banco de dados'
  replace:
    path: "{{ wp_installation_dir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"        
  loop:
    - { regex: 'database_name_here', value: "{{ wp_db_name }}"}
    - { regex: 'username_here', value: "{{ wp_username }}"}
    - { regex: 'password_here', value: "{{ wp_userpass }}"}
    - { regex: 'localhost', value: "{{ wp_dp_ip }}"}
  become: yes

- name: 'Configura Apache para servir Wordpress'
  template:
    src: '000-default.conf.j2'
    dest: '/etc/apache2/sites-available/000-default.conf'
  become: yes

- name: 'Configura porta do apache para servir wordpress'
  template:
    src: 'ports.conf.j2'
    dest: '/etc/apache2/ports.conf'
  become: yes

  notify:              
    - restart apache